# Site settings
title: Rabindra Lamsal
general_email: rabindralamsal@outlook.com
academic_email: 

description: > # this means to ignore newlines until "baseurl:"
  I'd say, I'm a deep learning enthusiast! In my case, the learning never saturates.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://www.rlamsal.com.np" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: rabindralamsal
linkedin_username: rabindralamsal
facebook_username: rabindralamsal
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
